### ISSUE TITLE
Error：IndexError: The shape of the mask [40, 40] at index 0 does not match the shape of the indexed tensor [80, 40, 40] at index 0

### ISSUE THREAD

**Issue by yuantao1880** [derronqi/yolov8-face#25]
HI，When I  infer using `yolov8n-face.engine`，it's not work，Has anyone encountered it？Details as below:
`Traceback (most recent call last):
  File "/home/admin/PycharmProjects/yolov8_face/inference_trt.py", line 360, in <module>
    face_det_results, full_frames, fps, img_size, static = pre_init(face=face, img_size=img_size)
  File "/home/admin/PycharmProjects/yolov8_face/inference_trt.py", line 189, in pre_init
    face_det_results.extend(face_detect(full_frames[idx:idx + yolo_batch], box=box, static=static, pads=pads, nosmooth=nosmooth))
  File "/home/admin/PycharmProjects/yolov8_face/yolov8_face.py", line 122, in face_detect
    face_det_results = face_detect_yolo(frames, pads=pads, nosmooth=nosmooth)  # BGR2RGB for CNN face detection
  File "/home/admin/PycharmProjects/yolov8_face/yolov8_face.py", line 43, in face_detect_yolo
    for result in results:
  File "/home/admin/miniconda3/envs/w2ltrt/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/admin/PycharmProjects/yolov8_face/yolov8-face/ultralytics/yolo/engine/predictor.py", line 256, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "/home/admin/PycharmProjects/yolov8_face/yolov8-face/ultralytics/yolo/v8/detect/predict.py", line 14, in postprocess
    preds = ops.non_max_suppression(preds,
  File "/home/admin/PycharmProjects/yolov8_face/yolov8-face/ultralytics/yolo/utils/ops.py", line 219, in non_max_suppression
    x = x[xc[xi]]  # confidence
IndexError: The shape of the mask [40, 40] at index 0 does not match the shape of the indexed tensor [80, 40, 40] at index 0`

**Comment by xxzznnn** [comment]
Hi, I encountered this problem too, have you fixed it?

**Comment by qwert1887** [comment]
> Hi, I encountered this problem too, have you fixed it?

Sorry,i finally give up.Hopefully someone can help us.
