### ISSUE TITLE
将Yolov8n 转换为ONNX模型后，使用YoloTracker会报错

### ISSUE THREAD

**Issue by quanqigu** [derronqi/yolov8-face#35]
首先感谢提供的yolo face模型。我在测试发现，
当我使用yolov8n-face.pt模型的时候，在ultratics中可以使用track。
但是当我转换为onnx后，就会报错。请问转换的时候 有什么需要注意的嘛？

转换代码如下
```
from ultralytics import YOLO
# Create a new YOLO model from scratch
model = YOLO("./yolov8n-face.pt")
# Export the model to ONNX format
success = model.export(format="onnx")
```

```
Traceback (most recent call last):
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/results.py", line 647, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 2
```

**Comment by quanqigu** [comment]
After disable the verbose to avoid getting here, it still report errors. From debug, looks like the box from track result is very bad.

What should I do? Is there something we need config to avoid such thing?

**Comment by quanqigu** [comment]
I have figured it out.
Looks like I have to specify the task to pose when using onnx model, but no need when using pt model.
```
success = model.export(format="onnx", dynamic=True, simplify=True)
model2 = YOLO("/xxx/models/yolov8n-face2.onnx", task='pose')
results[0].keypoints.xy.tolist()
```
